# Generated by Django 5.1.6 on 2025-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('file_pdf', models.FileField(upload_to='peraturan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
