# Generated by Django 5.1.6 on 2025-04-17 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPeraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('is_mobile_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Kategori Peraturan',
            },
        ),
        migrations.CreateModel(
            name='Kompilasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kompilasi Peraturan',
            },
        ),
        migrations.CreateModel(
            name='Peraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_peraturan', models.CharField(default='-', max_length=50)),
                ('nama_peraturan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('berlaku', 'Berlaku'), ('tidak berlaku', 'Tidak Berlaku')], default='berlaku', max_length=20)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('file_abstract', models.FileField(blank=True, null=True, upload_to='abstracts/')),
                ('file_pdf', models.FileField(upload_to='peraturan/')),
                ('teks_pdf', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori_peraturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeApp.kategoriperaturan')),
                ('kompilasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeApp.kompilasi')),
            ],
            options={
                'verbose_name_plural': 'Data Peraturan',
            },
        ),
    ]
