# Generated by Django 5.1.6 on 2025-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peraturan',
            name='teks_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
