# Generated by Django 5.1.6 on 2025-04-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peraturan',
            name='hanya_untuk_pegawai',
            field=models.BooleanField(default=False, help_text='Centang jika peraturan hanya untuk pegawai pesantren'),
        ),
    ]
