# Generated by Django 5.1.6 on 2025-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0002_peraturan_teks_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peraturan',
            old_name='judul',
            new_name='nama_peraturan',
        ),
        migrations.AddField(
            model_name='peraturan',
            name='kata_kunci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='peraturan',
            name='nomor_peraturan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peraturan',
            name='status',
            field=models.CharField(blank=True, choices=[('berlaku', 'Berlaku'), ('tidak berlaku', 'Tidak Berlaku')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peraturan',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
