# Generated by Django 5.1.6 on 2025-04-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0002_peraturan_hanya_untuk_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompilasi',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='kategori_peraturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeApp.kategoriperaturan'),
        ),
    ]
