# Generated by Django 5.1.6 on 2025-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0003_rename_judul_peraturan_nama_peraturan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peraturan',
            options={'verbose_name_plural': 'Data Peraturan'},
        ),
        migrations.AddField(
            model_name='peraturan',
            name='kategori_peraturan',
            field=models.CharField(blank=True, choices=[('kdp', 'Keputusan Dewan Pengasuh & Pengasuh'), ('pkp', 'Peraturan Kepala Pesantren'), ('pbb', 'Peraturan Biro, Badan & Banom'), ('psp', 'Peraturan Satuan Pendidikan'), ('sop', 'Standard Operating Procedure'), ('kpp', 'Kompilasi Peraturan Pesantren'), ('kp', 'Keputusan Pimpinan')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peraturan',
            name='lembar_pesantren',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='status',
            field=models.CharField(choices=[('berlaku', 'Berlaku'), ('tidak berlaku', 'Tidak Berlaku')], default='berlaku', max_length=50),
        ),
    ]
