# Generated by Django 5.1.6 on 2025-03-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0004_alter_peraturan_options_peraturan_kategori_peraturan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peraturan',
            name='kategori_peraturan',
            field=models.CharField(choices=[('kdp', 'Keputusan Dewan Pengasuh & Pengasuh'), ('pkp', 'Peraturan Kepala Pesantren'), ('pbb', 'Peraturan Biro, Badan & Banom'), ('psp', 'Peraturan Satuan Pendidikan'), ('sop', 'Standard Operating Procedure'), ('kpp', 'Kompilasi Peraturan Pesantren'), ('kp', 'Keputusan Pimpinan'), ('rc', 'Rancangan Hukum')], default='rc', max_length=50),
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='nomor_peraturan',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
