# Generated by Django 5.2.3 on 2025-09-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0004_alter_peraturan_nama_peraturan_kategoriaccessuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RancanganPeraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rancangan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('file_rancangan', models.FileField(upload_to='rancangan/')),
                ('status', models.CharField(choices=[('draft', 'Draft (baru diajukan)'), ('dalam_review', 'Dalam Review Admin'), ('diterima', 'Disetujui'), ('ditolak', 'Ditolak')], default='draft', max_length=20)),
                ('catatan_admin', models.TextField(blank=True, help_text='Catatan verifikasi dari admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori_peraturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeApp.kategoriperaturan')),
                ('pengusul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rancangan_pengusul', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rancangan Peraturan',
                'verbose_name_plural': 'Rancangan Peraturan',
            },
        ),
    ]
