# Generated by Django 5.1.6 on 2025-03-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0005_alter_peraturan_kategori_peraturan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPeraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategori Peraturan',
            },
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='status',
            field=models.CharField(choices=[('berlaku', 'Berlaku'), ('tidak berlaku', 'Tidak Berlaku')], default='berlaku', max_length=20),
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='kategori_peraturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeApp.kategoriperaturan'),
        ),
    ]
