# Generated by Django 5.1.6 on 2025-03-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0007_kategoriperaturan_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriperaturan',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='theme/static/img/dash/'),
        ),
    ]
