# Generated by Django 5.1.6 on 2025-03-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0009_alter_kategoriperaturan_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriperaturan',
            name='is_mobile_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
