# Generated by Django 5.1.6 on 2025-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0010_kategoriperaturan_is_mobile_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peraturan',
            name='kata_kunci',
        ),
        migrations.AddField(
            model_name='peraturan',
            name='file_abstract',
            field=models.FileField(blank=True, null=True, upload_to='abstracts/'),
        ),
    ]
